# Generated by Django 6.0.1 on 2026-01-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numner',
            new_name='phone_number',
        ),
    ]
